### ISSUE TITLE
Button Styles

### ISSUE THREAD

**Issue by schalkneethling** [mozilla/styleguide#1]
This issue lists all current and in use button styles.

**Comment by schalkneethling** [comment]
## Flat blue button

### HTML

As a link:

``` html
<a href="http://www.mozilla.org" class="button-blue more" role="button">Get the toolkit</a>
```

As a button element

``` html
<button class="button-blue more">Get the toolkit</button>
```

### Initial and visited state

![screen shot 2016-01-20 at 16 51 34](https://cloud.githubusercontent.com/assets/10350960/12452259/2e17aea6-bf96-11e5-8928-2cf7ad14ed10.png)

#### CSS

``` css
.button-blue,
.button-blue:link,
.button-blue:visited {
    display: block;
    background-color: #0C99D5;
    color: #fff;
    margin: 0 auto;
    padding: 10px 4px;
    border: none;
    border-radius: 6px;
    width: 250px;
    font-size: 0.875rem;
    font-weight: bold;
    text-transform: uppercase;
    text-align: center;
    text-decoration: none;
    cursor: pointer;
    transition: background-color 0.3s ease 0s;
}
```

### Hover and focus state

![screen shot 2016-01-20 at 16 51 44](https://cloud.githubusercontent.com/assets/10350960/12452288/5afa7412-bf96-11e5-94a3-cf9a5a6b7383.png)

#### CSS

``` css
.button-blue:hover,
.button-blue:focus {
    background-color: #2165A9;
    color: #fff;
}
```
